#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "datwaft"
email = "datwaftx@gmail.com"

[ui]
default-command = "log"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINtR9uu/tD0SNXfh75fS2sACiGlBMhxfhCxgbBsp+21i"
backends.ssh.program = "git-ssh-sign.sh"

[template-aliases]
'format_short_signature(signature)' = 'coalesce(signature.name(), signature.email())'
